import { MetadataRoute } from "next";
const pages: MetadataRoute.Sitemap = [
  {
    url: "",
    changeFrequency: "monthly",
    priority: 1,
    images: ["/prime-dubai-movers.jpg"],
    lastModified: "2026-01-15",
  },
  {
    url: "/contact",
    changeFrequency: "yearly",
    priority: 0.8,
    images: ["/prime-dubai-movers.jpg"],
    lastModified: "2026-01-15",
  },
  {
    url: "/free-quote",
    changeFrequency: "yearly",
    priority: 0.9,
    images: ["/prime-dubai-movers.jpg"],
    lastModified: "2026-01-15",
  },
  {
    url: "/about",
    changeFrequency: "yearly",
    priority: 0.9,
    images: ["/rime-dubai-movers-professional-team-dubai-marina-about-us.jpg"],
    lastModified: "2026-01-15",
  },
];
const locations: MetadataRoute.Sitemap = [
  {
    url: "/movers-packers/palm-jumeirah",
    images: ["/dub/Movers-and-Packers-in-Palm-Jumeirah.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/downtown-dubai",
    images: ["/dub/Movers-and-Packers-in-Downtown-Dubai.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/dubai-marina",
    images: ["/dub/Movers-and-Packers-in-Dubai-Marina.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/jvc",
    images: ["/dub/Movers-andPackers-in-JVC-Jumeirah-Village-Circle.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/jlt",
    images: ["/dub/Movers-and-Packers-in-JLT-Jumeirah-Lake-Towers.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/business-bay",
    images: ["/dub/Movers-and-Packers-in-Business-Bay.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/al-barsha",
    images: ["/dub/Movers-and-Packers-in-Al-Barsha-Dubai.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/arabian-ranches",
    images: ["/dub/Movers-and-Packers-in-Arabian-Ranches.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/emirates-hills",
    images: ["/dub/Movers-and-Packers-in-Emirates-Hills.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/damac-hills",
    images: ["/dub/Movers-and-Packers-in-Damac-Hills.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/al-nahda",
    images: ["/dub/Movers-and-Packers-in-Al-Nahda-Dubai.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/silicon-oasis",
    images: ["/dub/Movers-and-Packers-in-Dubai-Silicon-Oasis.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/bur-dubai",
    images: ["/dub/Movers-and-Packers-in-Bur-Dubai.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/deira",
    images: ["/dub/Movers-and-Packers-in-Deira-Dubai.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/al-quoz",
    images: ["/dub/Movers-and-Packers-in-Al-Quoz-Dubai.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/jvt",
    images: ["/dub/Movers-and-Packers-in-JVT-Jumeirah-Village-Triangle.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/motor-city",
    images: ["/dub/Movers-and-Packers-in-Motor-City-Dubai.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/international-city",
    images: ["/dub/Movers-and-Packers-in-International-City.jpg"],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/abu-dhabi",
    images: [`/loc/Movers-and-Packers-in-Abu-Dhabi.jpg`],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/sharjah",
    images: [`/loc/Movers-and-Packers-in-Sharjah.jpg`],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/ajman",
    images: [`/loc/Movers-and-Packers-in-Ajman.jpg`],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/ras-al-khaimah",
    images: [`/loc/Movers-and-Packers-in-Ras-Al-Khaimah.jpg`],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/fujairah",
    images: [`/loc/Movers-and-Packers-in-Fujairah.jpg`],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/umm-al-quwain",
    images: [`/loc/Movers-and-Packers-in-Umm-Al-Quwain.jpg`],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/al-ain",
    images: [`/loc/Movers-and-Packers-in-Al-Ain.jpg`],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/khalifa-city",
    images: [`/loc/Movers-and-Packers-in-Khalifa-City.jpg`],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/al-reem-island",
    images: [`/loc/Movers-and-Packers-in-Al-Reem-Island.jpg`],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/mussafah",
    images: [`/loc/Movers-and-Packers-in-Mussafah.jpg`],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/al-majaz",
    images: [`/loc/Movers-and-Packers-in-Al-Majaz-Sharjah.jpg`],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
  {
    url: "/movers-packers/al-nahda-sharjah",
    images: [`/loc/Movers-and-Packers-in-Al-Nahda-Sharjah.jpg`],
    changeFrequency: "monthly",
    priority: 0.8,
    lastModified: "2026-03-16",
  },
];

const services: MetadataRoute.Sitemap = [
  {
    url: "/house-movers-dubai",
    images: ["/House-Moving-in-Dubai.jpg"],
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-03-16",
  },
  {
    url: "/villa-movers-dubai",
    images: ["/Villa-Moving-in-Dubai.jpg"],
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-03-16",
  },
  {
    url: "/apartment-movers-dubai",
    images: ["/Apartment-Moving-in-Dubai.jpg"],
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-03-16",
  },
  {
    url: "/office-movers-dubai",
    images: ["/Office-Moving-in-Dubai.jpg"],
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-03-16",
  },
  {
    url: "/furniture-movers-dubai",
    images: ["/Furniture-Moving-in-Dubai.jpg"],
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-03-16",
  },
  {
    url: "/packing-services-dubai",
    images: ["/Packing-Services-in-Dubai.jpg"],
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-03-16",
  },
  {
    url: "/cheap-movers-dubai",
    images: ["/Cheap-Movers-in-Dubai.jpg"],
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-03-16",
  },
  {
    url: "/piano-movers-dubai",
    images: ["/Piano-Moving-in-Dubai.jpg"],
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-03-16",
  },
];
const furniture: MetadataRoute.Sitemap = [
  {
    url: "/used-furniture-buyers-dubai",
    images: ["/fur/used-furniture-buyers-in-dubai.jpg"],
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-03-16",
  },
  {
    url: "/used-furniture-buyers-abu-dhabi",
    images: ["/fur/used-furniture-buyers-in-abu-dhabi.jpg"],
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-03-16",
  },
  {
    url: "/used-furniture-buyers-sharjah",
    images: ["/fur/used-furniture-buyers-in-sharjah.jpg"],
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-03-16",
  },
  {
    url: "/used-furniture-buyers-ajman",
    images: ["/fur/used-furniture-buyers-in-ajman.jpg"],
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-03-16",
  },
  {
    url: "/used-furniture-buyers-al-ain",
    images: ["/fur/used-furniture-buyers-in-al-ain.jpg"],
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-03-16",
  },
  {
    url: "/used-furniture-buyers-ras-al-khaimah",
    images: ["/fur/used-furniture-buyers-in-ras-al-khaimah.jpg"],
    changeFrequency: "monthly",
    priority: 0.7,
    lastModified: "2026-03-16",
  },
];

export default function sitemap(): MetadataRoute.Sitemap {
  return [...pages, ...locations, ...services, ...furniture].map((page) => ({
    ...page,
    url: `${process.env.APP_URL}${page.url}`,
    images: page.images
      ? page.images.map((img) => `${process.env.APP_URL}${img}`)
      : [],
    lastModified: page.lastModified,
  }));
}
